(()=>{'use strict';
const F=window.FretQuest,courses=window.FQCourses,$=s=>document.querySelector(s),all=courses.flatMap(c=>c.lessons);
const labels={quiz:'理解をチェック',chord:'コード実践',pitch:'単音の音程',fret:'指板クイズ',rhythm:'リズム実践',ear:'聴き分け'};
const noteNames=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
let selected=courses[0],session=null,installPrompt=null,micActive=false;
function note(n){return noteNames[n%12]+(Math.floor(n/12)-1);}
function shuffle(a){const copy=[...a];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function unlocked(c,l){const i=c.lessons.indexOf(l);return i===0||!!F.getState().courses?.[c.lessons[i-1].id];}
function nextLesson(c){return c.lessons.find(l=>!F.getState().courses?.[l.id])||c.lessons[0];}
function render(){
 const state=F.getState(),done=all.filter(l=>state.courses?.[l.id]).length;
 $('#course-total').textContent=done+' / '+all.length;
 $('#course-overall-fill').style.width=done/all.length*100+'%';
 $('#course-grid').innerHTML=courses.map((c,i)=>{const n=c.lessons.filter(l=>state.courses?.[l.id]).length;return '<button type="button" class="course-book cover-'+c.color+(selected.id===c.id?' selected':'')+'" data-course="'+c.id+'" aria-pressed="'+(selected.id===c.id)+'"><div class="book-meta"><span>COURSE / 0'+(i+1)+'</span><span>'+c.level+'</span></div><div class="book-art">'+F.icon(c.icon)+'<span class="book-orbit"></span><span class="book-star">✦</span></div><h3>'+c.title+'</h3><p>'+c.subtitle+'</p><div class="book-foot"><span>'+n+' / 4 レッスン</span><span>'+(n===4?'✓ COMPLETE':'OPEN '+F.icon('arrow'))+'</span></div><div class="book-track"><span style="width:'+n/4*100+'%"></span></div></button>';}).join('');
 document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>{selected=courses.find(c=>c.id===b.dataset.course);render();$('#course-detail-title').focus({preventScroll:true});});
 const c=selected,n=c.lessons.filter(l=>state.courses?.[l.id]).length,next=nextLesson(c);
 $('#course-detail').className='course-detail cover-'+c.color;
 $('#course-detail').innerHTML='<div class="course-detail-top"><div><span class="kicker">YOUR NEXT SMALL WIN</span><h3 id="course-detail-title" tabindex="-1">'+c.title+'</h3><p>'+c.subtitle+' 各レッスンをクリアすると、次が開きます。</p></div><button type="button" class="primary-btn" id="continue-course">'+(n===4?'もう一度練習する':'続きから練習する')+' '+F.icon('arrow')+'</button></div><div class="lesson-path">'+c.lessons.map((l,i)=>{const d=state.courses?.[l.id],available=unlocked(c,l);return '<button type="button" class="course-lesson '+(d?'cleared':available?'available':'locked')+'" data-lesson="'+l.id+'" '+(!available?'disabled':'')+'><span class="lesson-stop">'+(d?F.icon('check'):available?String(i+1):'<span aria-hidden="true">⌑</span>')+'</span><span class="lesson-stop-copy"><strong>'+l.title+'</strong><small>'+labels[l.type]+' ・ 約'+l.minutes+'分</small></span><span class="lesson-stop-state">'+(d?'復習':available?'+40 XP':'前のレッスンで解放')+'</span></button>';}).join('')+'</div>';
 $('#continue-course').onclick=()=>open(c,next);
 document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{const l=c.lessons.find(x=>x.id===b.dataset.lesson);if(unlocked(c,l))open(c,l);});
}
function shell(l,stage,progress=0){return '<div class="lesson-progress">'+selected.title+' / '+stage+'</div><div class="lesson-bar"><span style="width:'+progress+'%"></span></div><h2 id="modal-title">'+l.title+'</h2>';}
function open(c,l){if(!unlocked(c,l)){F.notify('ひとつ前のレッスンをクリアしよう。');return;}selected=c;session={lesson:l,course:c,step:0,correct:0,method:'quiz',mode:'choose',automatic:0};F.show(el=>{
 el.innerHTML=shell(l,'LEARN')+'<p class="lesson-goal">'+l.goal+'</p><div class="teaching-cards">'+l.tips.map(([title,text],i)=>'<div class="teaching-card"><span>0'+(i+1)+'</span><div><h3>'+title+'</h3><p>'+text+'</p></div></div>').join('')+'</div>'+(l.exercise.previewChord?'<div class="intro-chord">'+F.chordDiagram(l.exercise.previewChord)+'</div>':'')+'<div class="lesson-ticket"><span>'+labels[l.type]+' ・ 約'+l.minutes+'分</span><span>初回クリア +40 XP</span></div><button type="button" class="action-button" id="lesson-begin">練習に進む '+F.icon('arrow')+'</button><p class="lesson-caption">'+(l.type==='pitch'?'マイク判定と自己チェックを選べます。音声の録音・送信は行いません。':l.type==='chord'?'コード演奏は自己チェックです。音程や押さえ方をマイクで判定しません。':'80％以上でクリア。間違えても、何度でも挑戦できます。')+'</p>';
 $('#lesson-begin').onclick=()=>{session.step=0;session.correct=0;run();};
 });
}
function run(){const l=session.lesson;if(l.type==='quiz'||l.type==='fret'||l.type==='ear')startQuiz();if(l.type==='chord')chordStep();if(l.type==='pitch')pitchStep();if(l.type==='rhythm')rhythm();}
function result(score,method,detail){const l=session.lesson,c=session.course;F.show(el=>{
 const passed=score>=80,earned=passed?F.recordLesson(l.id,score,method):0,next=c.lessons[c.lessons.indexOf(l)+1];
 el.innerHTML='<div class="modal-success">'+(earned?'<div class="confetti" aria-hidden="true">'+Array.from({length:20},(_,i)=>'<i style="--x:'+(5+i*4.5)+'%;--delay:'+(i%4*.06)+'s;--r:'+(i%2?200:-150)+'deg"></i>').join('')+'</div>':'')+'<div class="success-medal">'+F.icon(passed?'trophy':'pick')+'</div><div class="success-sub">'+(passed?'ONE MORE SMALL WIN.':'EVERY TRY COUNTS.')+'</div><h2 id="modal-title">'+(passed?'レッスン、クリア！':'もう一度、ゆっくり。')+'</h2><div class="success-xp">'+(earned?'+'+earned+' XP':score+'%')+'</div><p>'+detail+'</p><p>'+({self:'自己チェックでのクリアです。音程や演奏精度の自動採点ではありません。',microphone:'マイクで単音の音程を確認しました。リズムや運指の採点は含みません。',tap:'タップのタイミングと休符をチェックしました。',quiz:'理解をチェックしました。',ear:'三和音の聴き分けをチェックしました。'})[method]+'</p>'+(passed&&next?'<button class="action-button" id="lesson-next">次のレッスンへ '+F.icon('arrow')+'</button>':'')+'<button class="action-button '+(passed?'secondary-action':'')+'" id="lesson-retry">'+(passed?'もう一度練習する':'再挑戦する')+'</button><button class="action-button secondary-action" id="lesson-return">コースに戻る</button></div>';
 $('#lesson-next')?.addEventListener('click',()=>open(c,next));$('#lesson-retry').onclick=()=>open(c,l);$('#lesson-return').onclick=()=>{F.close();$('#courses').scrollIntoView({behavior:'smooth',block:'start'});};(passed&&next?$('#lesson-next'):$('#lesson-retry')).focus();
 });}
function startQuiz(){
 const l=session.lesson;session.method=l.type==='ear'?'ear':'quiz';
 if(!session.questions){session.questions=l.type==='fret'?shuffle(l.exercise.positions).map(([string,fret])=>{const tune=[64,59,55,50,45,40],answer=noteNames[(tune[string-1]+fret)%12],answers=shuffle([answer,...shuffle(noteNames.filter(n=>n!==answer)).slice(0,3)]);return {ask:string+'弦、'+fret+'フレットの音は？',answers,correct:answers.indexOf(answer),why:'標準チューニングで、この位置の音は '+answer+' です。',string,fret};}):l.type==='ear'?shuffle(l.exercise.questions).map(q=>({...q,ask:'この三和音は、メジャー？ マイナー？',answers:['メジャー','マイナー'],correct:q.minor?1:0,why:(q.minor?'短3度のマイナー':'長3度のメジャー')+'です。ルートと5度は同じで、3度の音が半音違います。'})):shuffle(l.exercise.questions);}
 const q=session.questions[session.step],total=session.questions.length;
 if(!q){result(Math.round(session.correct/total*100),session.method,total+'問中'+session.correct+'問正解。');return;}
 $('#modal-inner').innerHTML=shell(l,(session.step+1)+' / '+total,session.step/total*100)+'<p>'+q.ask+'</p>'+(q.string?F.fretDiagram(6-q.string,q.fret):'')+(l.type==='ear'?'<div class="ear-speaker">'+F.icon('music')+'</div><button class="action-button secondary-action" id="ear-play">お手本を聴く ♪</button>':'')+'<div class="answers">'+q.answers.map((a,i)=>'<button type="button" class="answer-button" data-choice="'+i+'">'+a+'</button>').join('')+'</div><div id="quiz-feedback" class="quiz-explanation" aria-live="polite"></div><button class="action-button" id="quiz-next" hidden>次へ '+F.icon('arrow')+'</button>';
 let answered=false,listened=l.type!=='ear';
 $('#ear-play')?.addEventListener('click',async()=>{const generation=F.generation();const button=$('#ear-play');button.disabled=true;const ok=await F.playTone(q.root,.9);if(generation!==F.generation())return;await F.playTone(q.root+(q.minor?3:4),.9);await F.playTone(q.root+7,.9);listened=ok;button.disabled=false;if(!ok)F.notify('音が使えません。端末の音量とブラウザを確認してください。');});
 document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(answered)return;if(!listened){F.notify('先に「お手本を聴く」で音を聴こう。');return;}answered=true;const hit=Number(b.dataset.choice)===q.correct;if(hit)session.correct++;b.classList.add(hit?'correct':'wrong');document.querySelectorAll('[data-choice]').forEach(x=>{x.disabled=true;if(Number(x.dataset.choice)===q.correct)x.classList.add('correct');});const spot=$('#spot-note');if(spot)spot.textContent=q.answers[q.correct];$('#quiz-feedback').textContent=(hit?'正解！ ':'正解は「'+q.answers[q.correct]+'」。 ')+q.why;$('#quiz-next').hidden=false;$('#quiz-next').focus();});
 $('#quiz-next').onclick=()=>{session.step++;startQuiz();};($('#ear-play')||$('.answer-button'))?.focus();
}
function chordStep(){const l=session.lesson,items=l.exercise.chords,target=items[session.step];session.method='self';if(!target){result(100,'self',items.length+'回のコード練習を自己チェックしました。');return;}
 $('#modal-inner').innerHTML=shell(l,(session.step+1)+' / '+items.length,session.step/items.length*100)+'<p>'+l.exercise.instruction+'</p><div class="chord-sequence">'+items.map((n,i)=>'<span class="'+(i===session.step?'current':i<session.step?'done':'')+'">'+n+'</span>').join('')+'</div><div class="chord-display"><div class="chord-target">'+target+'</div>'+F.chordDiagram(target)+'</div><div class="self-check-note">1本ずつ音を確認。×の弦は鳴らさず、白丸は開放弦です。</div><button class="action-button" id="chord-check">鳴らせた。次のコードへ '+F.icon('arrow')+'</button><button class="action-button secondary-action" id="chord-hint">押さえ方のコツを見る</button><p id="chord-help" class="lesson-caption" hidden>'+l.tips[0][1]+'</p>';
 $('#chord-check').onclick=()=>{session.step++;chordStep();};$('#chord-hint').onclick=()=>{$('#chord-help').hidden=!$('#chord-help').hidden;};$('#chord-check').focus();
}
function pitchStep(){const l=session.lesson,tones=l.exercise.tones,t=tones[session.step];if(!t){const automatic=session.automatic===tones.length;result(100,automatic?'microphone':'self',tones.length+'音を練習。'+session.automatic+'音をマイクで確認、'+(tones.length-session.automatic)+'音を自己チェックしました。');return;}if(session.mode==='self'){selfPitch();return;}
 $('#modal-inner').innerHTML=shell(l,(session.step+1)+' / '+tones.length,session.step/tones.length*100)+'<p>'+l.goal+'</p><div class="pitch-target"><span class="pitch-target-note">'+note(t.midi)+'</span><span>'+t.string+'弦 ・ '+t.fret+'フレット</span></div>'+F.fretDiagram(6-t.string,t.fret,note(t.midi))+'<div class="note-sequence">'+tones.map((n,i)=>'<span class="'+(i===session.step?'current':i<session.step?'done':'')+'">'+noteNames[n.midi%12]+'</span>').join('')+'</div><div class="mic-panel"><div class="mic-panel-top"><span id="mic-state">MIC / OFF</span><span>単音のみ</span></div><div class="detected-note" id="detected-note">♪</div><div class="tuning-meter"><span id="tuning-pointer"></span></div><p id="mic-feedback" aria-live="polite">音声はこの端末内で処理します。録音・送信はしません。</p></div><div class="pitch-actions"><button class="action-button" id="mic-start">マイクで音程を判定 '+F.icon('rhythm')+'</button><button class="action-button secondary-action" id="pitch-listen">お手本の音を聴く ♪</button><button class="action-button secondary-action" id="pitch-self">マイクを使わず自己チェック</button></div><p class="lesson-caption">チューニングを合わせ、他の弦を止めて1音ずつ。目安は±50セント以内です。コードや演奏のタイミングは判定しません。</p>';
 const spot=$('#spot-note');if(spot)spot.textContent=noteNames[t.midi%12];
 $('#pitch-listen').onclick=async()=>{const button=$('#pitch-listen'),generation=F.generation();button.disabled=true;await F.playTone(t.midi,.9);if(generation===F.generation()&&button.isConnected)button.disabled=false;};
 $('#pitch-self').onclick=()=>{session.mode='self';selfPitch();};$('#mic-start').onclick=()=>microphone(t);
 if(session.mode==='mic')$('#mic-feedback').textContent='次の音です。マイクを再開してから、1音だけ鳴らそう。';
}
function selfPitch(){const l=session.lesson,t=l.exercise.tones[session.step];F.show(el=>{el.innerHTML=shell(l,'SELF CHECK',session.step/l.exercise.tones.length*100)+'<p>表示の位置を押さえ、お手本と聴き比べて1音ずつ鳴らそう。</p><div class="pitch-target"><span class="pitch-target-note">'+note(t.midi)+'</span><span>'+t.string+'弦 ・ '+t.fret+'フレット</span></div>'+F.fretDiagram(6-t.string,t.fret,note(t.midi))+'<button class="action-button secondary-action" id="self-listen">お手本の音を聴く ♪</button><button class="action-button" id="self-note-next">弾けた。次の音へ '+F.icon('arrow')+'</button><p class="lesson-caption">自己チェックです。演奏の自動採点は行いません。</p>';$('#self-listen').onclick=()=>F.playTone(t.midi,.9);$('#self-note-next').onclick=()=>{session.step++;pitchStep();};});}
async function microphone(target){
 const generation=F.generation();if(!navigator.mediaDevices?.getUserMedia){F.notify('マイクが使えない環境です。自己チェックで練習できます。');return;}micActive=true;
 const button=$('#mic-start');button.disabled=true;$('#mic-feedback').textContent='マイクの許可を待っています。';
 let stream=null,context=null,source=null,analyser=null,timer=null,cancelled=false,stable=0;
 const stop=()=>{cancelled=true;micActive=false;clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop());source?.disconnect();analyser?.disconnect();if(context&&context.state!=='closed')context.close().catch(()=>{});};F.setCleanup(stop);
 try{
  context=new (window.AudioContext||window.webkitAudioContext)();await context.resume();
  if(cancelled||generation!==F.generation()){stop();return;}
  stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});
  if(cancelled||generation!==F.generation()){stop();return;}
  source=context.createMediaStreamSource(stream);analyser=context.createAnalyser();analyser.fftSize=4096;source.connect(analyser);
  const samples=new Float32Array(analyser.fftSize);let previousText='';session.mode='mic';$('#mic-state').textContent='MIC / LISTENING';button.disabled=false;button.textContent='■ マイクを停止';$('#pitch-listen').disabled=true;
  button.onclick=()=>{stop();$('#mic-state').textContent='MIC / OFF';$('#mic-feedback').textContent='マイクを停止しました。';$('#pitch-listen').disabled=false;button.textContent='マイクを再開';button.onclick=()=>microphone(target);};
  const poll=()=>{if(cancelled||generation!==F.generation())return;analyser.getFloatTimeDomainData(samples);const detected=window.FQPitch.detect(samples,context.sampleRate);let text='1音だけ、ゆっくり鳴らそう。';
   if(detected.frequency&&detected.clarity>.85){const f=detected.frequency,n=Math.round(window.FQPitch.midi(f)),offset=window.FQPitch.cents(f,target.midi);$('#detected-note').textContent=note(n);$('#tuning-pointer').style.left=(50+Math.max(-48,Math.min(48,offset/2)))+'%';const hit=Math.abs(offset)<=50;if(hit)stable++;else stable=0;text=hit?'いい音程！ そのまま響かせよう。':offset>0?'目標より高い音です。弦・フレットとチューニングを確認。':'目標より低い音です。弦・フレットとチューニングを確認。';
   }else{stable=0;$('#detected-note').textContent=detected.rms<.008?'♪':'…';}
   if(text!==previousText){$('#mic-feedback').textContent=text;previousText=text;}
   if(stable>=4){stop();$('#mic-state').textContent='MIC / MATCH';$('#mic-feedback').textContent='音程OK！ 音を止めてから次へ進もう。';button.textContent='音程OK。次の音へ '+ '→';button.disabled=false;button.onclick=()=>{session.automatic++;session.step++;pitchStep();};$('#pitch-listen').disabled=true;$('#pitch-self').disabled=true;return;}
   timer=setTimeout(poll,90);
  };poll();
 }catch(e){stop();if(generation!==F.generation())return;button.disabled=false;button.textContent='マイクを再試行';button.onclick=()=>microphone(target);$('#mic-state').textContent='MIC / OFF';$('#mic-feedback').textContent=e.name==='NotAllowedError'?'マイクの許可がありません。ブラウザ設定で許可するか、自己チェックで進めます。':e.name==='NotFoundError'?'マイクが見つかりません。自己チェックで練習できます。':'マイクを開始できませんでした。他のアプリが使用していないか確認してください。';}
}
function rhythm(){const l=session.lesson,e=l.exercise,interval=60000/e.bpm/e.subdivision;
 $('#modal-inner').innerHTML=shell(l,e.bpm+' BPM / '+(e.subdivision===4?'16':e.subdivision===2?'8':'4')+'分音符')+'<p>4拍のカウント後、丸の位置だけタップ。点は休符です。ヘッドホン推奨。</p><div class="rhythm-pattern">'+e.pattern.map((hit,i)=>'<span data-rhythm-cell="'+i+'" class="'+(hit?'hit':'rest')+'">'+(hit?'●':'·')+'</span>').join('')+'</div><div class="question-big" id="course-rhythm-count">READY?</div><button class="rhythm-pad" id="course-rhythm-pad" disabled>COUNT IN</button><button class="action-button" id="course-rhythm-start">リズム練習を始める</button><p class="lesson-caption">目標の拍に対して±'+Math.round(Math.min(150,interval*.3))+'ms以内を判定。余分なタップも結果に含みます。</p>';
 let timers=[],taps=[],targets=[],started=false,start=0;const stop=()=>{timers.forEach(clearTimeout);timers=[];started=false;};F.setCleanup(stop);
 const pad=$('#course-rhythm-pad');pad.onclick=()=>{if(started&&performance.now()>=start)taps.push(performance.now());};
 $('#course-rhythm-start').onclick=async()=>{const generation=F.generation(),button=$('#course-rhythm-start');button.disabled=true;await F.ensureAudio();if(generation!==F.generation())return;started=true;start=performance.now()+500+4*60000/e.bpm;
  for(let i=0;i<4;i++)timers.push(setTimeout(()=>{F.click(i===0);$('#course-rhythm-count').textContent='COUNT '+(i+1);},500+i*60000/e.bpm));
  e.pattern.forEach((hit,i)=>{const target=start+i*interval;if(hit)targets.push(target);timers.push(setTimeout(()=>{if(i===0){pad.disabled=false;pad.textContent='TAP!';}F.click(i%(4*e.subdivision)===0);document.querySelectorAll('[data-rhythm-cell]').forEach(cell=>cell.classList.toggle('playing',Number(cell.dataset.rhythmCell)===i));pad.classList.toggle('flash',!!hit);$('#course-rhythm-count').textContent='STEP '+(i+1)+' / '+e.pattern.length;},Math.max(0,target-performance.now())));});
  timers.push(setTimeout(()=>{const used=new Set();let hits=0;for(const target of targets){let best=-1,dist=Infinity;taps.forEach((time,i)=>{const d=Math.abs(time-target);if(!used.has(i)&&d<dist){dist=d;best=i;}});if(best>=0&&dist<=Math.min(150,interval*.3)){used.add(best);hits++;}}const extra=taps.length-hits,score=Math.max(0,Math.round((hits-extra)/targets.length*100));stop();result(score,'tap',targets.length+'音中'+hits+'音が範囲内。余分なタップは'+extra+'回でした。');},Math.max(0,start+e.pattern.length*interval-performance.now())+180));
 };
}
function transfer(){F.show(el=>{el.innerHTML='<div class="lesson-progress">YOUR PRACTICE, ANYWHERE</div><h2 id="modal-title">練習記録を持ち運ぶ</h2><p>XP、毎日の記録、コースのクリア状況をファイルに保存。別の端末で読み込めば、続きから練習できます。</p><div class="teaching-card"><div><h3>端末間の引き継ぎ</h3><p>① この端末で保存。② AirDropや自分宛の共有でファイルを移動。③ 移動先で読み込み。同じクリア記録は重複させずにまとめます。</p></div></div><button class="action-button" id="record-export">記録ファイルを保存</button><label class="import-label" for="record-import">記録ファイルを読み込む<input id="record-import" type="file" accept=".json,application/json"></label><div id="import-status" role="status" class="lesson-feedback"></div><p class="lesson-caption">アカウントによる自動同期には未対応です。読み込み前にも、現在の記録を保存できます。</p>';$('#record-export').onclick=()=>{const blob=new Blob([JSON.stringify(F.exportState(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='FRET_QUEST_'+F.today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('#record-import').onchange=async e=>{const generation=F.generation(),file=e.target.files[0];if(!file)return;if(file.size>2000000){$('#import-status').textContent='ファイルが大きすぎます。記録ファイルを選び直してください。';return;}try{const value=JSON.parse(await file.text());if(generation!==F.generation())return;F.importState(value);$('#import-status').textContent='読み込み完了。コースと練習記録を更新しました。';}catch(err){if(generation===F.generation())$('#import-status').textContent='読み込めません。FRET QUESTから保存したJSONファイルを選んでください。';}};});}
function install(){if(installPrompt){installPrompt.prompt();installPrompt=null;return;}F.show(el=>{el.innerHTML='<div class="lesson-progress">YOUR POCKET STUDIO</div><h2 id="modal-title">ホーム画面で、練習しよう。</h2><p>iPhoneではSafariでこのページを開き、共有メニューから「ホーム画面に追加」を選びます。</p><div class="teaching-card"><span>01</span><div><h3>Safariで開く</h3><p>アプリ内ブラウザから見ている場合は、Safariで開き直します。</p></div></div><div class="teaching-card"><span>02</span><div><h3>共有 → ホーム画面に追加</h3><p>FRET QUESTのアイコンから、練習画面をすぐに開けます。一度読み込んだレッスンはオフラインでも利用できます。</p></div></div><p class="lesson-caption">Webアプリとして追加します。App Store版ではありません。記録はブラウザごとに保存されるため、必要なら「記録を持ち運ぶ」で引き継ぎます。</p><button class="action-button" id="install-close">わかった</button>';$('#install-close').onclick=F.close;});}
$('#record-transfer').onclick=transfer;$('#app-install').onclick=install;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
window.addEventListener('fq:progress',render);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&micActive)F.close();});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>F.notify('オフライン保存を利用できません。オンラインでは練習できます。')));
render();
})();
