(()=>{'use strict';
const STORAGE='fretQuestV1';
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const defaults={xp:0,history:{},difficulty:'beginner'};
let data;try{data=JSON.parse(localStorage.getItem(STORAGE))||defaults}catch{data={...defaults}}if(!data||typeof data!=='object')data={...defaults};data.xp=Number(data.xp)||0;data.history=data.history&&typeof data.history==='object'?data.history:{};data.difficulty=['beginner','intermediate','advanced'].includes(data.difficulty)?data.difficulty:'beginner';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],day=()=>data.history[today()]||{quests:[],bonus:false};let activeCleanup=()=>{},toastTimeout=null;
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(data))}catch{notify('保存できません。ブラウザの設定をご確認ください。')}}
function notify(msg){const t=$('#toast');t.textContent=msg;t.classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>t.classList.remove('visible'),2900)}
function daysAgo(n){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-n);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function streak(){let count=0,n=0;if(!(data.history[today()]?.quests?.length))n=1;while(data.history[daysAgo(n)]?.quests?.length){count++;n++}return count}
function render(){const d=day(),completed=d.quests?.length||0;$('#streak-value').textContent=streak();$('#streak-sub').textContent=completed?'今日もナイスプレイ！':'今日のクエストを始めよう';$('#xp-value').textContent=data.xp;const level=Math.floor(data.xp/150)+1;$('#level-value').textContent=level;$('#level-needed').textContent='NEXT '+(150-data.xp%150)+' XP';$('#xp-fill').style.width=(data.xp%150/150*100)+'%';$('#mission-count').textContent=completed+' / 3';$('#daily-track-fill').style.width=completed/3*100+'%';$('#bonus-status').textContent=d.bonus?'✓ GET!':'+40 XP';$('#bonus-caption').textContent=d.bonus?'今日のボーナス獲得済み。明日も続けよう！':'3つ全部クリアで、さらに +40 XP';$$('[data-card]').forEach(card=>{const done=d.quests?.includes(card.dataset.card);card.classList.toggle('complete',!!done);card.querySelector('.quest-button').innerHTML=done?'もう一度 ↗':'挑戦する ↗'});const cal=$('#calendar-row');cal.innerHTML='';for(let i=13;i>=0;i--){const key=daysAgo(i),used=(data.history[key]?.quests?.length||0)>0;const el=document.createElement('span');el.className='calendar-day'+(used?' active':'');el.title=key+(used?' 練習済み':' 練習なし');el.textContent=new Date(key+'T12:00:00').getDate();cal.append(el)}const days=Object.values(data.history).filter(x=>x?.quests?.length).length;$('#practice-days').textContent='累計'+days+'日';const badges=[['🌱','初めの一歩',days>=1],['🔥','3日連続',streak()>=3],['⚡','XP 300',data.xp>=300],['🏆','7日連続',streak()>=7]];$('#badges').innerHTML=badges.map(([icon,label,yes])=>'<div class="badge '+(yes?'unlocked':'')+'" title="'+(yes?'達成済み':'未達成')+'"><div class="badge-icon">'+icon+'</div><small>'+label+'</small></div>').join('');$('#difficulty').value=data.difficulty;const dt=new Date();$('#today-label').textContent=new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'long'}).format(dt)+'  •  TODAY\'S SESSION'}
function complete(type,detail){const d=day();if(!Array.isArray(d.quests))d.quests=[];const first=!d.quests.includes(type);if(first){d.quests.push(type);data.xp+=30}if(d.quests.length===3&&!d.bonus){d.bonus=true;data.xp+=40}data.history[today()]=d;save();render();$('#modal-inner').innerHTML='<div class="modal-success"><div class="success-icon">🏆</div><div class="lesson-progress">QUEST COMPLETE</div><h2>ナイスプレイ！</h2><p>'+detail+'</p><p>'+(first?'+30 XP 獲得！':'復習完了！ XPは各クエスト1日1回獲得できます。')+(d.bonus&&first&&d.quests.length===3?' デイリーボーナス +40 XP！':'')+'</p><button class="action-button" id="success-close">ホームに戻る</button></div>';$('#success-close').onclick=closeModal;if(first)notify('+30 XP！ その調子！')}
function openModal(type){activeCleanup();activeCleanup=()=>{};$('#modal').hidden=false;document.body.style.overflow='hidden';if(type==='fret')startFret();if(type==='chord')startChord();if(type==='rhythm')startRhythm();$('#modal-close').focus()}
function closeModal(){activeCleanup();activeCleanup=()=>{};$('#modal').hidden=true;document.body.style.overflow=''}
$('#modal-close').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal').hidden)closeModal()});$$('[data-launch]').forEach(b=>b.onclick=()=>openModal(b.dataset.launch));$('#difficulty').onchange=e=>{data.difficulty=e.target.value;save();notify('難易度を変更しました')};
const notes=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'],tuning=[4,9,2,7,11,4];let fretQuestion=0,fretCorrect=0,locked=false;
function startFret(){fretQuestion=0;fretCorrect=0;nextFret()}
function nextFret(){if(fretQuestion>=8){complete('fret','8問中'+fretCorrect+'問正解。指板の音名を少しずつ覚えよう。');return}locked=false;const max=data.difficulty==='beginner'?5:data.difficulty==='intermediate'?12:20;const string=Math.floor(Math.random()*6),fret=Math.floor(Math.random()*(max+1)),correct=notes[(tuning[string]+fret)%12];const distractors=notes.filter(n=>n!==correct).sort(()=>Math.random()-.5).slice(0,3);const answers=[...distractors,correct].sort(()=>Math.random()-.5);$('#modal-inner').innerHTML='<div class="lesson-progress">FRETBOARD • '+(fretQuestion+1)+'/8</div><h2 id="modal-title">指板マスター</h2><p>標準チューニング（E A D G B E）。次の位置の音名は？</p><div class="question-big">'+(6-string)+'弦 ・ '+fret+'フレット</div><div class="answers">'+answers.map(n=>'<button type="button" class="answer-button" data-answer="'+n+'">'+n+'</button>').join('')+'</div><div class="lesson-feedback" id="fret-feedback"></div>';$$('[data-answer]').forEach(b=>b.onclick=()=>{if(locked)return;locked=true;fretQuestion++;const hit=b.dataset.answer===correct;if(hit)fretCorrect++;$$('[data-answer]').forEach(x=>{x.disabled=true;if(x.dataset.answer===correct)x.classList.add('correct')});$('#fret-feedback').textContent=hit?'正解！':'正解は '+correct+' です。';const id=setTimeout(nextFret,850);activeCleanup=()=>clearTimeout(id)})}
let chordInterval=null,chordSeconds=35,chordSwitches=0,chordStarted=false,chordIndex=0;
const chordSets={beginner:['Em','G','C','D','Am'],intermediate:['F','Bm','G','D','A','E'],advanced:['F♯m7','B7','C♯m','Emaj7','B♭','G♯m']};
function startChord(){chordSeconds=35;chordSwitches=0;chordStarted=false;chordIndex=0;const set=chordSets[data.difficulty];$('#modal-inner').innerHTML='<div class="lesson-progress">CHORD CHANGE • 35 SECONDS</div><h2 id="modal-title">コード・チェンジ</h2><p>表示されたコードをギターで押さえ、音を鳴らしたら「次のコード」を押して切り替えよう。これは自己申告型の練習です。</p><div class="chord-target" id="chord-target">'+set[0]+'</div><div class="timer-big" id="chord-timer">0:35</div><p style="text-align:center">切り替え回数 <strong id="chord-count">0</strong> 回</p><button class="action-button" id="chord-action">▶ 35秒チャレンジ開始</button>';$('#chord-action').onclick=()=>{if(!chordStarted){chordStarted=true;$('#chord-action').textContent='次のコード ↗';chordInterval=setInterval(()=>{chordSeconds--;$('#chord-timer').textContent='0:'+String(chordSeconds).padStart(2,'0');if(chordSeconds<=0){clearInterval(chordInterval);chordInterval=null;complete('chord',chordSwitches+'回のコード切り替えに挑戦しました。') }},1000);activeCleanup=()=>clearInterval(chordInterval)}else{chordSwitches++;chordIndex=(chordIndex+1)%set.length;$('#chord-target').textContent=set[chordIndex];$('#chord-count').textContent=chordSwitches}}}
let rhythmTimers=[],rhythmTaps=[],rhythmTarget=[],rhythmStarted=false;function clearRhythm(){rhythmTimers.forEach(clearTimeout);rhythmTimers=[];rhythmStarted=false}function startRhythm(){clearRhythm();rhythmTaps=[];rhythmTarget=[];const bpm=data.difficulty==='beginner'?75:data.difficulty==='intermediate'?100:130;const interval=60000/bpm;$('#modal-inner').innerHTML='<div class="lesson-progress">RHYTHM • '+bpm+' BPM</div><h2 id="modal-title">リズム・キーパー</h2><p>最初の4拍はカウント。続く8拍で光る円に合わせてタップしよう。音も鳴ります。ヘッドホン推奨。</p><div class="question-big" id="rhythm-score">READY?</div><button class="rhythm-pad" type="button" id="rhythm-pad" disabled>COUNT IN</button><button class="action-button" id="rhythm-start">▶ スタート</button><div class="lesson-feedback" id="rhythm-feedback"></div>';const pad=$('#rhythm-pad');pad.onclick=()=>{if(!rhythmStarted||!rhythmTarget.length)return;rhythmTaps.push(performance.now());pad.classList.add('flash');setTimeout(()=>pad.classList.remove('flash'),90)};$('#rhythm-start').onclick=async()=>{if(rhythmStarted)return;await ensureAudio();rhythmStarted=true;$('#rhythm-start').disabled=true;$('#rhythm-start').textContent='演奏中';const start=performance.now()+450;for(let i=0;i<12;i++){const id=setTimeout(()=>{soundClick(i%4===0);pad.classList.add('flash');setTimeout(()=>pad.classList.remove('flash'),100);$('#rhythm-score').textContent=i<4?'COUNT '+(i+1):'BEAT '+(i-3)+' / 8';if(i===4){pad.disabled=false;pad.textContent='TAP!'}if(i>=4)rhythmTarget.push(performance.now())},Math.max(0,start+i*interval-performance.now()));rhythmTimers.push(id)}rhythmTimers.push(setTimeout(()=>{pad.disabled=true;pad.textContent='FINISH!';const targets=rhythmTarget;const taps=[...rhythmTaps],used=new Set();let hits=0;for(const target of targets){let best=-1,dist=Infinity;taps.forEach((t,i)=>{const d=Math.abs(t-target);if(!used.has(i)&&d<dist){best=i;dist=d}});if(best>=0&&dist<=Math.min(220,interval*.32)){used.add(best);hits++}}clearRhythm();complete('rhythm','8拍中'+hits+'拍がタイミング範囲内でした。'+(hits<5?'次は一定のテンポを意識してみよう。':'グッドグルーヴ！'))},Math.max(0,start+12*interval-performance.now())+250));activeCleanup=clearRhythm}}
let audio=null;async function ensureAudio(){try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')await audio.resume()}catch{notify('この端末では音が使えません')}}function soundClick(accent=false){if(!audio||audio.state!=='running')return;const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(accent?1060:740,t);o.frequency.exponentialRampToValueAtTime(accent?520:410,t+.045);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(accent?.21:.13,t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+.075);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.08)}
let bpm=90,metroInterval=null,metroBeat=0;const dots=$$('.beat-dots span');function setBpm(n){bpm=Math.max(40,Math.min(220,n));$('#bpm-value').textContent=bpm;$('#bpm-slider').value=bpm;if(metroInterval){stopMetro();startMetro()}}function metroTick(){soundClick(metroBeat%4===0);dots.forEach((d,i)=>d.classList.toggle('lit',i===metroBeat%4));metroBeat++}async function startMetro(){await ensureAudio();metroBeat=0;metroTick();metroInterval=setInterval(metroTick,60000/bpm);$('#metro-toggle').textContent='■ ストップ';$('#metro-toggle').classList.add('running');$('#metro-status').textContent='PLAYING'}function stopMetro(){clearInterval(metroInterval);metroInterval=null;dots.forEach(d=>d.classList.remove('lit'));$('#metro-toggle').textContent='▶ スタート';$('#metro-toggle').classList.remove('running');$('#metro-status').textContent='READY'}$('#metro-toggle').onclick=()=>metroInterval?stopMetro():startMetro();$$('[data-bpm]').forEach(b=>b.onclick=()=>setBpm(bpm+Number(b.dataset.bpm)));$('#bpm-slider').oninput=e=>setBpm(Number(e.target.value));$$('.nav-link').forEach(a=>a.addEventListener('click',()=>{$$('.nav-link').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));document.addEventListener('visibilitychange',()=>{if(document.hidden&&metroInterval)stopMetro()});window.addEventListener('pagehide',()=>{stopMetro();activeCleanup()});render();
})();